
service: e-neural-crud
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20211008
  stage: dev
  region: us-east-1
  environment:
    CANDIDATE_TABLE: "candidate-${opt:stage, self:provider.stage}"
    CANDIDATE_EMAIL_TABLE: "candidate-email-${opt:stage, self:provider.stage}"
    CHAT_TABLE: "chat-${opt:stage, self:provider.stage}"
    API_REGION: "${self:provider.region}" 
  iamRoleStatements:
    # - Effect: Allow
    #   Action:
    #     - "execute-api:ManageConnections"
    #   Resource:
    #     - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

  # optional
  # websocketApiName: websocket-chat-${self:provider.stage}

  # required for websocket apis
  # this selects from your payload what your "routeKey" parameter is
  # from the websocket event types on your function
  # websocketApiRouteSelectionExpression: $request.body.action

plugins:
  - serverless-websockets-plugin
functions:
  tokenValidate:
    handler: modules/auth/tokenValidate.handler

  publicEndpoint:
    handler: modules/public/public.list
    memorySize: 128
    description: Lista candidates public.
    events:
      - http:
          path: api/public
          method: get
          cors: true

  candidateSubmission:
    handler: modules/api/candidate.submit
    memorySize: 128
    description: Submit candidate information and starts interview process.
    events:
      - http: 
          path: api/candidates
          method: post
          cors: true
          authorizer: tokenValidate

  listCandidates:
    handler: modules/api/candidate.list
    memorySize: 128
    description: List all candidates
    events:
      - http: 
          path: api/candidates
          method: get
          cors: true
          authorizer: tokenValidate

  candidateDetails:
    handler: modules/api/candidate.get
    memorySize: 128
    description: List id candidate
    events:
      - http:
          path: api/candidates/{id}
          method: get
          cors: true
          authorizer: tokenValidate

  # manage connection and disconnection of clients
  # connectionManager:
  #   handler: modules/chat/handler.connectionManager
  #   events:
  #     - websocket:
  #         routeKey: $connect
  #     - websocket:
  #         routeKey: $disconnect

  # # just in case we are getting weird / bad data
  # # we can react to it with a sane response
  # defaultMessages:
  #   handler: modules/chat/handler.defaultMessage
  #   events:
  #     - websocket:
  #         routeKey: $default

  # # handle chat app messages
  # sendMessage:
  #   handler: modules/chat/handler.sendMessage
  #   events:
  #     - websocket:
  #         routeKey: sendMessage

  # # Channel Subscriptions
  # channelManager:
  #   handler: modules/chat/handler.channelManager
  #   events:
  #     - websocket:
  #         routeKey: subscribeChannel
  #     - websocket:
  #         routeKey: unsubscribeChannel

  # # handle broadcasting all events
  # # we do this by listening the dynamodb table stream for messages or disconnects
  # # could even be done by sub-systems directly to dynamodb
  # broadcast:
  #   handler: modules/chat/handler.broadcast
  #   events:
  #     - stream:
  #         type: dynamodb
  #         arn:
  #           Fn::GetAtt: [ApplicationDynamoDBTable, StreamArn]  

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"
        TableName: ${self:provider.environment.CANDIDATE_TABLE}
    CandidateEmailDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "email"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "email"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.CANDIDATE_EMAIL_TABLE}
